"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _transactions_summary from './transactions-summary.bones.json'
import _transactions from './transactions.bones.json'
import _account_summary from './account-summary.bones.json'
import _accounts from './accounts.bones.json'
import _budgets from './budgets.bones.json'
import _categories from './categories.bones.json'
import _dashboard_balance from './dashboard-balance.bones.json'
import _dashboard_budgets from './dashboard-budgets.bones.json'
import _dashboard_savings from './dashboard-savings.bones.json'
import _dashboard_summary from './dashboard-summary.bones.json'
import _subscriptions from './subscriptions.bones.json'

configureBoneyard({"color":"var(--gris)","darkColor":"var(--gris)","animate":"solid","boneClass":"skeleton"})

registerBones({
  "transactions-summary": _transactions_summary,
  "transactions": _transactions,
  "account-summary": _account_summary,
  "accounts": _accounts,
  "budgets": _budgets,
  "categories": _categories,
  "dashboard-balance": _dashboard_balance,
  "dashboard-budgets": _dashboard_budgets,
  "dashboard-savings": _dashboard_savings,
  "dashboard-summary": _dashboard_summary,
  "subscriptions": _subscriptions,
})
